name: build webapp

on:
    push:
        branches:
            - main
            - "test/*"
    pull_request:
        types: [assigned, opened, synchronize, reopened, labeled]
        paths:
            - ".eslintignore"
            - ".eslintrc.js"
            - ".prettierrc.json"
            - "lerna.json"
            - "packages"
            - "package.json"
            - "tsconfig.build.json"
            - "tsconfig.json"
            - "yarn.lock"

jobs:
    build:
        name: Build Eden Community WebApp
        runs-on: ubuntu-latest

        steps:
            - name: ✅ Checkout code
              uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: "14"

            - name: 🛠 Build
              run: |
                  yarn install
                  yarn build --stream

            - name: 🧪 Check server is running healthy
              run: cd build && ctest -j$(nproc)

            # build and publish webapp (todo: when we fix webapp-builder)
