name: build

on:
    push:
        branches:
            - main
            - "test/*"
        paths:
            - "docker/eden-builder.Dockerfile"
    pull_request:
        types: [assigned, opened, synchronize, reopened, labeled]
        paths:
            - "docker/eden-builder.Dockerfile"

jobs:
    build:
        name: Updates Eden Builder Image
        runs-on: ubuntu-latest

        steps:
            - name: ✅ Checkout code
              uses: actions/checkout@v2

            - name: Preparation
              id: prep
              run: |
                  REGISTRY="docker.pkg.github.com"
                  IMAGE="${REGISTRY}/${{ github.repository }}/${{ github.event.repository.name }}-eden-builder"
                  TAGS="${IMAGE}:${{ github.sha }}"
                  if [[ $GITHUB_REF == ref/head/master ]]; then
                    TAGS="${TAGS},${IMAGE}:latest"
                  fi
                  echo ::set-output name=tags::${TAGS}

            - name: Docker Buildx setup
              uses: docker/setup-buildx-action@v1

            - name: Login in to registry
              uses: docker/login-action@v1
              with:
                  registry: docker.pkg.github.com
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: 🛠 Build & Publish Image
              uses: docker/build-push-action@v2
              with:
                  push: true
                  file: docker/eden-builder.Dockerfile
                  tags: ${{ steps.prep.outputs.tags.outputs.lowercase }}
