name: eden-builder container

on:
    push:
        branches:
            - main
            - "test/*"
        paths:
            - "docker/eden-builder.Dockerfile"
    pull_request:
        types: [assigned, opened, synchronize, reopened, labeled]
        paths:
            - "docker/eden-builder.Dockerfile"

jobs:
    build:
        name: Updates Eden Builder Image
        runs-on: ubuntu-latest

        steps:
            - name: ✅ Checkout code
              uses: actions/checkout@v2

            - name: Preparation
              id: prep
              run: |
                  REGISTRY="ghcr.io"
                  IMAGE="${REGISTRY}/${{ github.repository_owner }}/eden-builder"
                  TAGS="${IMAGE}:${{ github.sha }}"
                  if [[ $GITHUB_REF == ref/head/master ]]; then
                    TAGS="${TAGS},${IMAGE}:latest"
                  fi
                  echo ::set-output name=tags::${TAGS,,}

            - name: Showtag
              id: showtag
              run: echo ${{ steps.prep.outputs.tags }}

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Docker Buildx setup
              uses: docker/setup-buildx-action@v1
              with:
                  buildkitd-flags: --debug

            - name: Set up containerd
              uses: crazy-max/ghaction-setup-containerd@v1

            - name: 🛠 Build & Publish Image
              uses: docker/build-push-action@v2
              with:
                  file: docker/eden-builder.Dockerfile
                  tags: ghcr.io/eoscommunity/eden-builder:latest
                  outputs: type=oci,dest=/tmp/image.tar

            - name: Import image in containerd
              run: |
                  sudo ctr i import --base-name ghcr.io/eoscommunity/eden-builder --digests --all-platforms /tmp/image.tar

            - name: Push image with containerd
              run: |
                  sudo ctr --debug i push --user "${{ github.repository_owner }}:${{ secrets.GITHUB_TOKEN }}" ghcr.io/eoscommunity/eden-builder:latest
