name: job-dev-test
on:
    push:
        branches:
            - "sparkplug0025/*" # todo: remove it before merging
    schedule:
        - cron: "*/2 * * * *"
jobs:
    cron:
        runs-on: ubuntu-latest
        steps:
            - name: Test Job
              run: |
                  curl --request POST \
                  --url 'https://eden-dev.vercel.app/api/jobs/test' \
                  --header 'x-job-key: ${{ secrets.DEV_JOBS_AUTH_GC }}'
